name: ➕ Request New Rate
description: Request a new mortgage rate or lender to be added
title: "[Rate] Add rate from "
labels: ["rate-data", "enhancement"]
body:
  - type: dropdown
    id: lender
    attributes:
      label: Lender
      description: Which lender offers this rate?
      options:
        - AIB
        - Avant Money
        - Bank of Ireland
        - Credit Union Mortgages
        - Permanent TSB
        - Other
    validations:
      required: true

  - type: input
    id: rate-description
    attributes:
      label: Rate Description
      description: Describe the rate (e.g., type, term, LTV, percentage)
      placeholder: "e.g., 3-year fixed at 3.45% up to 80% LTV"
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Source
      description: Link to the lender's website or other source
      placeholder: "https://..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details about this rate (BER requirements, minimum loan, etc.)

  - type: checkboxes
    id: publicly-available
    attributes:
      label: Confirmation
      options:
        - label: This rate is publicly available and not a privately offered rate from a lender
          required: true
