name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: not-rate-request
    attributes:
      label: Confirmation
      options:
        - label: This is not a request to add new rate data (use "Request New Rate" template for that)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: "A clear description of the feature..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful? What problem does it solve?
      placeholder: "This would help me..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, examples, or any other details
